// Generated by CoffeeScript 1.8.0
var Quicksetup, p,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Quicksetup = (function() {
  function Quicksetup(path) {
    this.path = path;
    this.showCoupon = __bind(this.showCoupon, this);
    this.showService = __bind(this.showService, this);
    this.showGroup = __bind(this.showGroup, this);
    this.showServices = __bind(this.showServices, this);
    this.showInfo = __bind(this.showInfo, this);
    this.defaultClose = __bind(this.defaultClose, this);
    this.setActive = __bind(this.setActive, this);
    this.closeActive = __bind(this.closeActive, this);
    this.active = "";
    this.container = "#full_container";
  }

  Quicksetup.prototype.getConfig = function() {
    return $.getJSON("" + this.path + "/config").done((function(_this) {
      return function(data) {
        _this.config = data.content;
        return _this.setupNav();
      };
    })(this));
  };

  Quicksetup.prototype.closeActive = function() {
    if (this["close" + this.active] != null) {
      return this["close" + this.active]();
    } else {
      return this.defaultClose();
    }
  };

  Quicksetup.prototype.setActive = function(name) {
    if (this.active === name || !this.closeActive()) {
      return false;
    }
    this.active = name;
    return true;
  };

  Quicksetup.prototype.defaultClose = function() {
    this.active = "";
    $(this.container).empty();
    return true;
  };

  Quicksetup.prototype.setContainer = function(val) {
    return $(this.container).html(val);
  };

  Quicksetup.prototype.setupNav = function() {
    $("#menuInfo").click((function(_this) {
      return function(e) {
        e.preventDefault();
        return _this.showInfo();
      };
    })(this));
    $("#menuServices").click((function(_this) {
      return function(e) {
        e.preventDefault();
        return _this.showServices();
      };
    })(this));
    this.showInfo();
    return $(".navbar-brand").html(this.config.name);
  };

  Quicksetup.prototype.showInfo = function() {
    if (!this.setActive("Info")) {
      return false;
    }
    return $.getJSON("" + this.path + "/get_store_info").done((function(_this) {
      return function(data) {
        return _this.setContainer(Handlebars.compile($("#storeinfo").html())(_this.config));
      };
    })(this));
  };

  Quicksetup.prototype.showServices = function() {
    if (!this.setActive("Services")) {
      return false;
    }
    return $.getJSON("" + this.path + "/get_services").done((function(_this) {
      return function(data) {
        _this.setContainer(Handlebars.compile($("#servicelist").html())(data.content));
        $("#addgroup").click(function(e) {
          e.preventDefault();
          return _this.showGroup();
        });
        $("a[id^='add_']").click(function(e) {
          e.preventDefault();
          return _this.showService(0, $(e.currentTarget).attr("data-id"));
        });
        $("a[id^='group_']").click(function(e) {
          e.preventDefault();
          return _this.showGroup($(e.currentTarget).attr("data-id"));
        });
        $("a[id^='service_']").click(function(e) {
          e.preventDefault();
          return _this.showService($(e.currentTarget).attr("data-id"), 0);
        });
        $("#addcoupon").click(function(e) {
          e.preventDefault();
          return _this.showCoupon();
        });
        return $("a[id^='coupon_']").click(function(e) {
          e.prevetDefault();
          return _this.showCoupon($(e.currentTarget).attr("data-id"));
        });
      };
    })(this));
  };

  Quicksetup.prototype.showGroup = function(id) {
    var grouptpl;
    if (id == null) {
      id = 0;
    }
    if (!this.setActive("Group")) {
      return false;
    }
    grouptpl = (function(_this) {
      return function(data) {
        _this.setContainer(Handlebars.compile($("#groupedit").html())(data ? data.content : null));
        $("#savebtn").click(function(e) {
          e.preventDefault();
          return $.post("" + _this.path + "/save_group", $("#groupform").serialize(), null, "json").done(function(data) {
            e.preventDefault();
            return _this.showServices();
          });
        });
        return $("#cancelbtn").click(function(e) {
          e.preventDefault();
          return _this.showServices();
        });
      };
    })(this);
    if (id === 0) {
      return grouptpl();
    } else {
      return $.getJSON("" + this.path + "/get_group/" + id).done(function(data) {
        return grouptpl(data);
      });
    }
  };

  Quicksetup.prototype.showService = function(id, group) {
    if (id == null) {
      id = 0;
    }
    if (group == null) {
      group = 0;
    }
    if (!this.setActive("Service")) {
      return false;
    }
    return $.getJSON("" + this.path + "/get_service/" + group + "/" + id).done((function(_this) {
      return function(data) {
        _this.setContainer(Handlebars.compile($("#serviceedit").html())(data.content));
        $("#savebtn").click(function(e) {
          e.preventDefault();
          return $.post("" + _this.path + "/save_service", $("#serviceform").serialize(), null, "json").done(function(data) {
            e.preventDefault();
            return _this.showServices();
          });
        });
        return $("#cancelbtn").click(function(e) {
          e.preventDefault();
          return _this.showServices();
        });
      };
    })(this));
  };

  Quicksetup.prototype.showCoupon = function(id) {
    var coupontpl;
    if (id == null) {
      id = 0;
    }
    if (!this.setActive("Coupon")) {
      return false;
    }
    coupontpl = (function(_this) {
      return function(data) {
        _this.setContainer(Handlebars.compile($("#couponedit").html())(data ? data.content : null));
        $("#savebtn").click(function(e) {
          e.preventDefault();
          return $.post("" + _this.path + "/save_coupon", $("#couponform").serialize(), null, "json").done(function(data) {
            return _this.showServices();
          });
        });
        return $("#cancelbtn").click(function(e) {
          e.preventDefault();
          return _this.showServices();
        });
      };
    })(this);
    if (id === 0) {
      return coupontpl();
    } else {
      return $.getJSON("" + this.path + "/get_coupon/" + id).done(function(data) {
        return coupontpl(data);
      });
    }
  };

  return Quicksetup;

})();

p = new Quicksetup(window.basepath);

$(document).ready(function() {
  Handlebars.registerHelper('formatMoney', function(val) {
    if (val < 0) {
      val = val * -1;
    }
    return "" + (Number(val).toFixed(2));
  });
  Handlebars.registerHelper('isChecked', function(expr) {
    if (Number(expr)) {
      return 'checked';
    } else {
      return '';
    }
  });
  Handlebars.registerHelper('isSelected', function(v1, v2) {
    if (v1 === v2) {
      return 'selected';
    } else {
      return '';
    }
  });
  Handlebars.registerHelper('ifEqOr', function(v1, v2, v3, options) {
    if (v1 === v2 || v1 === v3) {
      return options.fn(this);
    } else {
      return options.inverse(this);
    }
  });
  Handlebars.registerHelper('ifNegative', function(val, options) {
    if (val < 0) {
      return options.fn(this);
    } else {
      return options.inverse(this);
    }
  });
  return p.getConfig();
});
